### Get all contacts
GET https://cse341-evvf.onrender.com/contacts


### Get a single contact by ID
GET https://cse341-evvf.onrender.com/contacts/6829188589a379815e78ced1


### Create a new contact
POST https://cse341-evvf.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "KEvin",
  "lastName": "Smith",
  "email": "randomprophet@lds.org",
  "favoriteColor": "Black",
  "birthday": "1972-02-19"
}


### Update a contact by ID
PUT https://cse341-evvf.onrender.com/contacts/6829188589a379815e78ced1
Content-Type: application/json

{
  "firstName": "Batman",
  "lastName": "Wayne",
  "email": "darkknight@justiceleague.org",
  "favoriteColor": "Dark Gray",
  "birthday": "1999-12-25"
}


### Delete a contact by ID
DELETE https://cse341-evvf.onrender.com/contacts/6829188589a379815e78ced1
