### Get all Pokémon
GET https://cse341-s9x3.onrender.com/pokemons

### Create a Pokémon
POST https://cse341-s9x3.onrender.com/pokemons
Content-Type: application/json

{
  "name": "Pikachu",
  "type": "Electric",
  "releaseDate": "1996-02-27"
}

### PUT update
PUT https://cse341-s9x3.onrender.com/pokemons/6832313e70d9328e68bbdc5c
Content-Type: application/json

{
  "name": "Charmander",
  "type": "Fire",
  "releaseDate": "1996-02-27"
}

### DELETE
DELETE https://cse341-s9x3.onrender.com/pokemons/6832249281a22867a131d762





### GET all moves
GET https://cse341-s9x3.onrender.com/moves

### GET one move
GET https://cse341-s9x3.onrender.com/moves/{id}

### POST a new move
POST https://cse341-s9x3.onrender.com/moves
Content-Type: application/json

{
  "name": "Thunderbolt",
  "type": "Electric",
  "power": 90
}

### PUT update a move
PUT https://cse341-s9x3.onrender.com/moves/6832316970d9328e68bbdc5e
Content-Type: application/json

{
  "name": "Thunderbolt",
  "type": "Electric",
  "power": 95
}

### DELETE a move
DELETE https://cse341-s9x3.onrender.com/moves/{id}
