### Get all Pokémon
GET https://cse341-s9x3.onrender.com/pokemons

### Create a Pokémon
POST https://cse341-s9x3.onrender.com/pokemons
Content-Type: application/json

{
  "name": "Pikachu",
  "type": "Electric",
  "releaseDate": "1996-02-27"
}
