@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NTM0OTQ1M2VhYjBkN2U5YWNhYjczNiIsImVtYWlsIjoiYXNoQGV4YW0uY29tIiwiaWF0IjoxNzUwMjk4MDUxLCJleHAiOjE3NTAzMDE2NTF9.-BRbAkChoALQxNvUBPV9Y1QdsJDk0dZiPgaWb3qzZIQ

#######################################################################################
### Authentication

### Signup (Create a Trainer)
POST https://cse341-s9x3.onrender.com/auth/signup
Content-Type: application/json

{
  "name": "Ash Ketchum",
  "email": "ash@exam.com",
  "password": "pikachu123"
}

### Login and get JWT token
POST https://cse341-s9x3.onrender.com/auth/login
Content-Type: application/json

{
  "email": "ash@exam.com",
  "password": "pikachu123"
}


#######################################################################################
### Trainers

### Get all Trainers
GET https://cse341-s9x3.onrender.com/trainers
Authorization: Bearer {{token}}

### Get a Trainer by ID
GET https://cse341-s9x3.onrender.com/trainers/6853490da0fc92f12375a20e
Authorization: Bearer {{token}}

### Update a Trainer
PUT https://cse341-s9x3.onrender.com/trainers/6853490da0fc92f12375a20e
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Ash K.",
  "email": "ash@example.com",
  "password": "newpass456"
}

### Delete a Trainer
DELETE https://cse341-s9x3.onrender.com/trainers/{trainerId}
Authorization: Bearer {{token}}


#######################################################################################
### Pokémon

### Get all Pokémon
GET https://cse341-s9x3.onrender.com/pokemon

### Get a Pokémon by ID
GET https://cse341-s9x3.onrender.com/pokemon/{pokemonId}

### Create a new Pokémon
POST https://cse341-s9x3.onrender.com/pokemon
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Charmander",
  "type": ["Fire"],
  "level": 12,
  "trainer": "Ash"
}

### Update a Pokémon
PUT https://cse341-s9x3.onrender.com/pokemon/{pokemonId}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Charmeleon",
  "type": ["Fire"],
  "level": 22,
  "trainer": "Ash"
}

### Delete a Pokémon
DELETE https://cse341-s9x3.onrender.com/pokemon/{pokemonId}
Authorization: Bearer {{token}}


#######################################################################################
### Items

### Get all Items
GET https://cse341-s9x3.onrender.com/items

### Get an Item by ID
GET https://cse341-s9x3.onrender.com/items/{itemId}

### Create a new Item
POST https://cse341-s9x3.onrender.com/items
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Potion",
  "effect": "Heals 20 HP",
  "quantity": 5,
  "trainer": "Ash"
}

### Update an Item
PUT https://cse341-s9x3.onrender.com/items/{itemId}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Super Potion",
  "effect": "Heals 50 HP",
  "quantity": 2,
  "trainer": "Ash"
}

### Delete an Item
DELETE https://cse341-s9x3.onrender.com/items/{itemId}
Authorization: Bearer {{token}}


#######################################################################################
### Battles

### Get all Battles
GET https://cse341-s9x3.onrender.com/battles

### Get a Battle by ID
GET https://cse341-s9x3.onrender.com/battles/{battleId}

### Create a new Battle
POST https://cse341-s9x3.onrender.com/battles
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "trainer1": "Ash",
  "trainer2": "Gary",
  "pokemon1": "Pikachu",
  "pokemon2": "Blastoise",
  "winner": "Ash",
  "location": "Pallet Town"
}

### Update a Battle
PUT https://cse341-s9x3.onrender.com/battles/{battleId}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "trainer1": "Ash",
  "trainer2": "Gary",
  "pokemon1": "Squirtle",
  "pokemon2": "Ponyta",
  "winner": "Pepe",
  "location": "Pallet Town"
}

### Delete a Battle
DELETE https://cse341-s9x3.onrender.com/battles/{battleId}
Authorization: Bearer {{token}}
